name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Markdown lint
        uses: articulate/action-markdownlint@v1
        with:
          config: .github/markdownlint/config.json
          files: '**/*.md'